version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: rest-spring-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restSpring
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local

